// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mxsmJsonProtobuf.proto

package com.github.mxsm.springboot.protobuf;

public final class MessageDto {
  private MessageDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MxsmDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mxsm1.MxsmDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Any details = 1;</code>
     * @return Whether the details field is set.
     */
    boolean hasDetails();
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     * @return The details.
     */
    com.google.protobuf.Any getDetails();
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getDetailsOrBuilder();
  }
  /**
   * Protobuf type {@code mxsm1.MxsmDto}
   */
  public static final class MxsmDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mxsm1.MxsmDto)
      MxsmDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MxsmDto.newBuilder() to construct.
    private MxsmDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MxsmDto() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MxsmDto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MxsmDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (details_ != null) {
                subBuilder = details_.toBuilder();
              }
              details_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(details_);
                details_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.springboot.protobuf.MessageDto.internal_static_mxsm1_MxsmDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.springboot.protobuf.MessageDto.internal_static_mxsm1_MxsmDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto.class, com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto.Builder.class);
    }

    public static final int DETAILS_FIELD_NUMBER = 1;
    private com.google.protobuf.Any details_;
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     * @return Whether the details field is set.
     */
    @java.lang.Override
    public boolean hasDetails() {
      return details_ != null;
    }
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     * @return The details.
     */
    @java.lang.Override
    public com.google.protobuf.Any getDetails() {
      return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
    }
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
      return getDetails();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (details_ != null) {
        output.writeMessage(1, getDetails());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (details_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDetails());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto)) {
        return super.equals(obj);
      }
      com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto other = (com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto) obj;

      if (hasDetails() != other.hasDetails()) return false;
      if (hasDetails()) {
        if (!getDetails()
            .equals(other.getDetails())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDetails()) {
        hash = (37 * hash) + DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getDetails().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mxsm1.MxsmDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mxsm1.MxsmDto)
        com.github.mxsm.springboot.protobuf.MessageDto.MxsmDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.mxsm.springboot.protobuf.MessageDto.internal_static_mxsm1_MxsmDto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.mxsm.springboot.protobuf.MessageDto.internal_static_mxsm1_MxsmDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto.class, com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto.Builder.class);
      }

      // Construct using com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (detailsBuilder_ == null) {
          details_ = null;
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.mxsm.springboot.protobuf.MessageDto.internal_static_mxsm1_MxsmDto_descriptor;
      }

      @java.lang.Override
      public com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto getDefaultInstanceForType() {
        return com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto build() {
        com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto buildPartial() {
        com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto result = new com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto(this);
        if (detailsBuilder_ == null) {
          result.details_ = details_;
        } else {
          result.details_ = detailsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto) {
          return mergeFrom((com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto other) {
        if (other == com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto.getDefaultInstance()) return this;
        if (other.hasDetails()) {
          mergeDetails(other.getDetails());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Any details_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       * @return Whether the details field is set.
       */
      public boolean hasDetails() {
        return detailsBuilder_ != null || details_ != null;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       * @return The details.
       */
      public com.google.protobuf.Any getDetails() {
        if (detailsBuilder_ == null) {
          return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
        } else {
          return detailsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder setDetails(com.google.protobuf.Any value) {
        if (detailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          details_ = value;
          onChanged();
        } else {
          detailsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder setDetails(
          com.google.protobuf.Any.Builder builderForValue) {
        if (detailsBuilder_ == null) {
          details_ = builderForValue.build();
          onChanged();
        } else {
          detailsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder mergeDetails(com.google.protobuf.Any value) {
        if (detailsBuilder_ == null) {
          if (details_ != null) {
            details_ =
              com.google.protobuf.Any.newBuilder(details_).mergeFrom(value).buildPartial();
          } else {
            details_ = value;
          }
          onChanged();
        } else {
          detailsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder clearDetails() {
        if (detailsBuilder_ == null) {
          details_ = null;
          onChanged();
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public com.google.protobuf.Any.Builder getDetailsBuilder() {
        
        onChanged();
        return getDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
        if (detailsBuilder_ != null) {
          return detailsBuilder_.getMessageOrBuilder();
        } else {
          return details_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : details_;
        }
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDetailsFieldBuilder() {
        if (detailsBuilder_ == null) {
          detailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getDetails(),
                  getParentForChildren(),
                  isClean());
          details_ = null;
        }
        return detailsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mxsm1.MxsmDto)
    }

    // @@protoc_insertion_point(class_scope:mxsm1.MxsmDto)
    private static final com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto();
    }

    public static com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MxsmDto>
        PARSER = new com.google.protobuf.AbstractParser<MxsmDto>() {
      @java.lang.Override
      public MxsmDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MxsmDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MxsmDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MxsmDto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.mxsm.springboot.protobuf.MessageDto.MxsmDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mxsm1_MxsmDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mxsm1_MxsmDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026mxsmJsonProtobuf.proto\022\005mxsm1\032\031google/" +
      "protobuf/any.proto\"0\n\007MxsmDto\022%\n\007details" +
      "\030\001 \001(\0132\024.google.protobuf.AnyB1\n#com.gith" +
      "ub.mxsm.springboot.protobufB\nMessageDtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_mxsm1_MxsmDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mxsm1_MxsmDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mxsm1_MxsmDto_descriptor,
        new java.lang.String[] { "Details", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
